/* GAME HUB OF SIR — Home application */
"use strict";

const games = [
  {id:1,name:"Reaction Time Test",icon:"⚡",description:"Test your reaction speed.",page:"reaction.html",category:"skill"},{id:2,name:"Coin Toss",icon:"🪙",description:"Flip a virtual coin.",page:"coin.html",category:"casual"},{id:22,name:"Whack The Alien",icon:"👽",description:"Whack aliens before time runs out.",page:"alien.html",category:"arcade"},{id:3,name:"Dice Roller",icon:"🎲",description:"Roll a random dice.",page:"dice.html",category:"casual"},{id:4,name:"Tic Tac Toe",icon:"❌",description:"Classic XO strategy game.",page:"tic.html",category:"brain"},{id:5,name:"Spin The Wheel",icon:"🎡",description:"Spin and get a surprise.",page:"wheel.html",category:"casual"},{id:6,name:"Truth Or Dare",icon:"🤔",description:"Play a fun round with friends.",page:"truth.html",category:"casual"},{id:7,name:"Random Challenge",icon:"🎯",description:"Complete a fun challenge.",page:"challenge.html",category:"skill"},{id:8,name:"Aim Trainer",icon:"🎯",description:"Improve your aiming skill.",page:"aim.html",category:"skill"},{id:23,name:"Banana Slip Battle",icon:"🍌",description:"Dodge banana peels and stay on your feet.",page:"banana.html",category:"arcade"},{id:9,name:"Jump Game",icon:"🦘",description:"Jump over obstacles and survive.",page:"jump.html",category:"arcade"},{id:10,name:"Memory Match",icon:"🧠",description:"Match emoji pairs and train your brain.",page:"memory.html",category:"brain"},{id:11,name:"Rock Paper Scissors",icon:"✊",description:"Play against the computer.",page:"rps.html",category:"casual"},{id:12,name:"Mind Reader",icon:"🔮",description:"Think of a number and test the magic.",page:"mindreader.html",category:"brain"},{id:14,name:"Balloon Pop",icon:"🎈",description:"Pop balloons before the timer ends.",page:"balloon.html",category:"arcade"},{id:15,name:"Neon Catcher",icon:"🌌",description:"Catch glowing neon orbs.",page:"neon.html",category:"arcade"},{id:16,name:"Rocket Dodge",icon:"🚀",description:"Dodge asteroids in an endless space runner.",page:"rocket.html",category:"space"},{id:17,name:"Thunder Tap",icon:"⚡",description:"Test your lightning-fast reaction speed.",page:"thunder.html",category:"skill"},{id:18,name:"Target Storm",icon:"🎯",description:"Hit targets, avoid bombs and build combos.",page:"target.html",category:"skill"},{id:20,name:"Animation Gallery",icon:"🎬",description:"Explore beautiful interactive particle animations.",page:"animation.html",category:"casual"},{id:21,name:"Cosmic Odyssey",icon:"🌌",description:"Travel into deep space and escape the black hole.",page:"cosmic.html",category:"space"},{id:24,name:"Penguin Slide",icon:"🐧",description:"Slide across the ice, collect fish and avoid holes.",page:"penguin.html",category:"arcade"}
];
const KEY={recent:"gh_recent_v2",favorites:"gh_favorites_v2",plays:"gh_plays_v2",theme:"gh_theme_v2"};
const read=(key,fallback)=>{try{const raw=localStorage.getItem(key);return raw===null?fallback:JSON.parse(raw)}catch{return fallback}};
const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
function escapeHtml(value){const d=document.createElement("div");d.textContent=String(value);return d.innerHTML}
function findGame(id){return games.find(g=>g.id===Number(id))}
function applyTheme(theme){document.documentElement.dataset.theme=theme;const btn=$("#themeBtn");if(btn){btn.textContent=theme==="dark"?"☀️":"🌙";btn.setAttribute("aria-label",theme==="dark"?"Switch to light mode":"Switch to dark mode")}write(KEY.theme,theme)}
function initTheme(){const saved=read(KEY.theme,null);const theme=saved||(matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light");applyTheme(theme);$("#themeBtn")?.addEventListener("click",()=>applyTheme(document.documentElement.dataset.theme==="dark"?"light":"dark"))}
function card(game){const favorites=read(KEY.favorites,[]),plays=read(KEY.plays,{}),fav=favorites.includes(game.id),count=Number(plays[game.id]||0);return `<article class="hub-card" data-id="${game.id}"><div class="hub-card-top"><span class="hub-game-icon" aria-hidden="true">${game.icon}</span><button class="hub-fav ${fav?"active":""}" data-favorite="${game.id}" type="button" aria-label="${fav?"Remove from favorites":"Add to favorites"}" aria-pressed="${fav}">${fav?"♥":"♡"}</button></div><span class="hub-category">${escapeHtml(game.category)}</span><h3>${escapeHtml(game.name)}</h3><p>${escapeHtml(game.description)}</p><div class="hub-card-meta"><span>${count?`${count.toLocaleString()} ${count===1?"play":"plays"}`:"New game"}</span></div><button class="hub-play" data-play="${game.id}" type="button">Play now <span aria-hidden="true">→</span></button></article>`}
function trackPlay(game){const recent=read(KEY.recent,[]).filter(id=>id!==game.id);recent.unshift(game.id);write(KEY.recent,recent.slice(0,8));const plays=read(KEY.plays,{});plays[game.id]=(Number(plays[game.id])||0)+1;write(KEY.plays,plays)}
function render(list,target){const el=$(target);if(el)el.innerHTML=list.map(card).join("")}
function renderHome(category="all",query=""){const q=query.trim().toLowerCase(),filtered=games.filter(g=>(category==="all"||g.category===category)&&(!q||`${g.name} ${g.description}`.toLowerCase().includes(q)));const empty=$("#noGame");render(filtered,"#gamesContainer");if(empty)empty.hidden=filtered.length>0;const featuredSection=$("#featuredSection");if(category==="all"&&!q){const plays=read(KEY.plays,{});const featured=games.slice().sort((a,b)=>(Number(plays[b.id]||0)-Number(plays[a.id]||0))||(a.id-b.id)).slice(0,6);render(featured,"#featuredGames");if(featuredSection)featuredSection.hidden=false}else if(featuredSection)featuredSection.hidden=true;const recent=read(KEY.recent,[]).map(findGame).filter(Boolean),recentEl=$("#recentSection");if(recentEl){if(recent.length&&!q&&category==="all"){render(recent,"#recentGames");recentEl.hidden=false}else recentEl.hidden=true}updateStats()}
function updateStats(){const plays=read(KEY.plays,{}),fav=read(KEY.favorites,[]),total=Object.values(plays).reduce((a,b)=>a+Number(b||0),0);const a=$("#heroGameCount"),b=$("#heroPlayed"),c=$("#heroFavorites");if(a)a.textContent=games.length;if(b)b.textContent=total;if(c)c.textContent=fav.length}
function openGame(id){const game=findGame(id);if(!game)return;trackPlay(game);window.location.href=game.page}
function closeMobileMenu(){const menu=$("#mobileHubMenu"),btn=$("#mobileMenuBtn");if(menu){menu.hidden=true;btn?.setAttribute("aria-expanded","false")}}
function init(){initTheme();let category="all";renderHome();$("#searchInput")?.addEventListener("input",e=>renderHome(category,e.target.value));$$(".hub-filter").forEach(btn=>btn.addEventListener("click",()=>{$$(".hub-filter").forEach(b=>b.classList.remove("active"));btn.classList.add("active");category=btn.dataset.category;renderHome(category,$("#searchInput")?.value||"")}));document.addEventListener("click",e=>{const play=e.target.closest("[data-play]");if(play){e.stopPropagation();openGame(play.dataset.play);return}const fav=e.target.closest("[data-favorite]");if(fav){const id=Number(fav.dataset.favorite);let list=read(KEY.favorites,[]);list=list.includes(id)?list.filter(x=>x!==id):[...list,id];write(KEY.favorites,list);renderHome(category,$("#searchInput")?.value||"");return}const clear=e.target.closest("[data-clear-recent]");if(clear){write(KEY.recent,[]);renderHome(category,$("#searchInput")?.value||"");return}if(!e.target.closest("#mobileHubMenu,#mobileMenuBtn"))closeMobileMenu()});$("[data-scroll-games]")?.addEventListener("click",()=>$("#gamesSection")?.scrollIntoView({behavior:"smooth",block:"start"}));const menu=$("#mobileHubMenu"),menuBtn=$("#mobileMenuBtn");menuBtn?.addEventListener("click",e=>{e.stopPropagation();const open=!menu.hidden;menu.hidden=open;menuBtn.setAttribute("aria-expanded",String(!open))});$$("#mobileHubMenu a").forEach(a=>a.addEventListener("click",closeMobileMenu));document.addEventListener("keydown",e=>{if(e.key==="Escape")closeMobileMenu()});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}))}
document.addEventListener("DOMContentLoaded",init);
